### ISSUE TITLE
Suggested Changes to R Documentation for Easier UX

### ISSUE THREAD

**Issue by DougVegas** [AdrianAntico/RemixAutoML#1]
1) can we change "is the source time series data.table" to "is the source time series data as a data.table (use package data.table to convert data.frame to data.table)"

2) In the Lags argument, can we change "same with moving averages" as "same as moving average lags"

3) In the SLags argument, can we change "same with moving averages" as "same as moving average lags"

**Comment by AdrianAntico** [comment]
Changed 1. to #' @param data is the source time series data as a data.table - or a data structure that can be converted to a data.table.
2 and 3 are good to go

**Comment by DougVegas** [comment]
In AutoTS documentation, can we also change default value in TargetName from "Targets" to "TargetMetric" as the word "Targets" may imply you can send more than 1 target value?

**Comment by DougVegas** [comment]
Also, can we add the following to the Description of the AutoTS function in RemixAutoML. I'm copying+pasting from the README.md file:

Automatically finds the best model fit from the suite of models below (using optimized box-cox transformations), along with generating forecasts and evaluation metrics.

Models include:

- ARIFIMA: Auto Regressive Fractional Integrated Moving Average
- ARIMIA: Stepwise Auto Regressive Integrated Moving Average with specified max lags, seasonal lags, moving averages, and seasonal moving averages
- ETS: Additive and Multiplicitive Exponential Smoothing and Holt Winters
- NNetar: Auto Regressive Neural Network models automatically compares models with 1 lag or 1 seasonal lag compared to models with up to N lags and N seasonal lags
- TBATS: Exponential smoothing state space model with Box-Cox transformation, ARMA errors, Trend and Seasonal components
- TSLM: Time Series Linear Model - builds a linear model with trend and season components extracted from the data
- Prophet: Additive model where non-linear trends are fit with yearly, weekly, and daily seasonality, plus holiday effects
