### ISSUE TITLE
 Undefined exports: AutoCatBoostCARMA

### ISSUE THREAD

**Issue by mileta1976** [AdrianAntico/RemixAutoML#12]
Hello,

There is an error during installation:
"Error: package or namespace load failed for ‘RemixAutoML’ in namespaceExport(ns, exports):
 undefined exports: AutoCatBoostCARMA"

It is possible there is an error in NAMESPACE file and export()

Thank you !

**Comment by AdrianAntico** [comment]
I did some work on the RemixAutoML file today by adding that function in there. I was able to download it just now. Can you try again and let me know if there is still an error?

**Comment by mileta1976** [comment]
It  is OK now.
Thank you for your support !

**Comment by AdrianAntico** [comment]
Sorry for confusion!
