### ISSUE TITLE
exampl

### ISSUE THREAD

**Issue by VladPerervenko** [AdrianAntico/RemixAutoML#14]
`Error in AutoXGBoostClassifier(data, ValidationData = NULL, TestData = NULL,  : 
  object 'CatFeatures' not found`
What is it?

**Comment by AdrianAntico** [comment]
I recently updated the code for that function. Originally, I had an argument for naming which columns were categorical. I removed that argument and just handled that internally. I forgot to remove a line of code that referenced the argument that no longer exists. Go ahead and rerun the install code and you should be good to go.
```{r}
devtools::install_github('AdrianAntico/RemixAutoML', 
                          upgrade = FALSE, 
                          dependencies = FALSE, 
                          force = TRUE) 
```

**Comment by VladPerervenko** [comment]
its OK now,
Good luck

**Comment by AdrianAntico** [comment]
Thanks for identifying the issue and bringing it up here!
