### ISSUE TITLE
Error [object 'TransformationResults' not found] when try code in Article

### ISSUE THREAD

**Issue by Arrow72** [AdrianAntico/RemixAutoML#16]
When I try reproduce code from article https://www.remixinstitute.com/blog/automated-demand-forecasts-using-autocatboostcarma-in-r/#.XRNZaExuLvU 
I have error:
```
> Results <- RemixAutoML::AutoCatBoostCARMA(
+   data,
+   TargetColumnName = "Weekly_Sales",
+   DateColumnName = "Date",
+   GroupVariables = c("Store","Dept"),
+   FC_Periods = 52,
+   TimeUnit = "week",
+   TargetTransformation = TRUE,
+   Lags = c(1:25, 51, 52, 53),
+   MA_Periods = c(1:25, 51, 52, 53),
+   CalendarVariables = TRUE,
+   TimeTrendVariable = TRUE,
+   DataTruncate = FALSE,
+   SplitRatios = c(1 - 2*30/143, 30/143, 30/143),
+   TaskType = "GPU",
+   EvalMetric = "MAE",
+   GridTune = FALSE,
+   GridEvalMetric = "mae",
+   ModelCount = 1,
+   NTrees = 200,
+   PartitionType = "timeseries",
+   Timer = TRUE)
...
bestTest = 104.8901737
bestIteration = 199
Shrink model to first 200 iterations.
Error in AutoCatBoostRegression(data = train, ValidationData = valid,  : 
  object 'TransformationResults' not found
```

**Comment by AdrianAntico** [comment]
Go ahead and reinstall and give it another shot. Should be good to go now.

**Comment by BadriPrudhvi** [comment]
Hi Adrian,
Firstly, this is a fantastic package. Thanks for your amazing work.

When I run my model, I am seeing this error. Please suggest.

Error in data.table::rbindlist(list(TransformObject, data.table::data.table(ColumnName = "Predict",  : 
  object 'TransformObject' not found

**Comment by AdrianAntico** [comment]
There was a missing if(TargetTransformation) before the operation listed in your error print out. I just updated the file. You'll need to reinstall. And thanks for the compliment!

**Comment by Arrow72** [comment]
Thanks! After reinstall it worked fine!

**Comment by Arrow72** [comment]
Hi, have new strange error on my own data:
```
Results <- AutoCatBoostCARMA(dat,
                             TargetColumnName = "TARGET",
                             DateColumnName = "WEEK",
                             GroupVariables = c("SKU_CODE","PARTNER_CODE"),
                             FC_Periods = 7,
                             TimeUnit = "week",
                             TargetTransformation = TRUE,
                             Lags = c(1:5),
                             MA_Periods = c(1:5),
                             CalendarVariables = TRUE,
                             TimeTrendVariable = TRUE,
                             DataTruncate = FALSE,
                             SplitRatios = c(1-2*30/143,30/143,30/143),
                             TaskType = "GPU",
                             EvalMetric = "MAE",
                             GridTune = FALSE,
                             GridEvalMetric = "mae",
                             ModelCount = 1,
                             NTrees = 200,
                             PartitionType = "time")
....
190:	learn: 2.1882090	test: 4.0409398	best: 4.0409398 (190)	total: 8.06s	remaining: 380ms
199:	learn: 2.0430123	test: 3.9538488	best: 3.9538488 (199)	total: 8.47s	remaining: 0us
bestTest = 3.953848775
bestIteration = 199
Shrink model to first 200 iterations.
Error in `[.data.table`(MetricCollection, , `:=`(eval(GroupVariables),  : 
  Supplied 2 columns to be assigned 6 items. Please see NEWS for v1.12.2.
```

**Comment by Arrow72** [comment]
in prev example i have SKU_CODE:number, and PARTNER_CODE:string
when i convert PARTNER_CODE tp number a have this:
```
199:	learn: 2.2547473	test: 4.7852071	best: 4.7852071 (199)	total: 4.56s	remaining: 0us
bestTest = 4.785207113
bestIteration = 199
Shrink model to first 200 iterations.
[1] "Forecast future step:  1"
Error in if (min(as.ITime(data[[eval(DateCols[i])]])) - max(as.ITime(data[[eval(DateCols[i])]])) ==  : 
  missing value where TRUE/FALSE needed
```

**Comment by BadriPrudhvi** [comment]
The previous issue got fixed after I reinstalled the package. However, I am seeing this new issue. Please help.

`999:	learn: 24.2476734	test: 56.4998953	best: 56.4998953 (999)	total: 1m 20s	remaining: 0us

bestTest = 56.49989532
bestIteration = 999

Dataset is provided, but PredictionValuesChange feature importance don't use it, since non-empty LeafWeights in model.
[1] "Forecast future step:  1"
Error in RemixAutoML::AutoCatBoostScoring(TargetType = "regression", ScoringData = UpdateData[.N,  : 
  unused argument (FeatureColNames = setdiff(names(UpdateData), c("Predictions", eval(DateColumnName), eval(TargetColumnName))))`

**Comment by AdrianAntico** [comment]
Can you guys send over an example (subset of your data) that I can run? This will make troubleshooting a lot easier. If you have several examples, send them all over. Make sure the data types are exactly what you want.

**Comment by BadriPrudhvi** [comment]
Hi Adrian,

I am just using the code snippet in the examples to test the function

`
library(RemixAutoML)
library(data.table)

data <- data.table(DateTime = as.Date(Sys.time()),
                   Target = stats::filter(rnorm(1000 ,mean=50, sd=20), filter=rep(1,10), circular=TRUE))
data[, temp := seq(1:1000)][, DateTime := DateTime - temp][, temp := NULL]
data <- data[order(DateTime)]
Results <- AutoCatBoostCARMA(data,
                             TargetColumnName = "Target",
                             DateColumnName = "DateTime",
                             FC_Periods = 30,
                             TimeUnit = "day",
                             TargetTransformation = FALSE,
                             Lags = c(1:5),
                             MA_Periods = c(1:5),
                             CalendarVariables = TRUE,
                             TimeTrendVariable = TRUE,
                             DataTruncate = FALSE,
                             SplitRatios = c(0.9,0.05,0.05),
                             TaskType = "CPU",
                             EvalMetric = "MAE",
                             GridTune = FALSE,
                             GridEvalMetric = "mae",
                             ModelCount = 1,
                             NTrees = 1000,
                             PartitionType = "time")`

**Comment by AdrianAntico** [comment]
Can you try changing the target variable name to something other than "Target"?

**Comment by BadriPrudhvi** [comment]
I have changed and tried but I see the same issue.

**Comment by AdrianAntico** [comment]
@BadriPrudhvi  I was able to track down the error. Internally, for the modeling case without a grouping variable, the AutoCatBoostScoring() function call had an argument that was named incorrectly (was FeatureColNames when it should have been FeatureColumnNames). Go ahead and reinstall and it should work fine. The code snippet below should run faster if you want to confirm results a bit faster.

Thanks for letting me know about the issue!

``` {r}
data <- data.table(DateTime = as.Date(Sys.time()),
                   Target = stats::filter(rnorm(1000 ,mean=50, sd=20), filter=rep(1,10), circular=TRUE))
data[, temp := seq(1:1000)][, DateTime := DateTime - temp][, temp := NULL]
data <- data[order(DateTime)]
Results <- AutoCatBoostCARMA(data,
                             TargetColumnName = "Target",
                             DateColumnName = "DateTime",
                             GroupVariables = NULL,
                             FC_Periods = 30,
                             TimeUnit = "day",
                             TargetTransformation = FALSE,
                             Lags = c(1:5),
                             MA_Periods = c(1:5),
                             CalendarVariables = TRUE,
                             TimeTrendVariable = TRUE,
                             DataTruncate = FALSE,
                             SplitRatios = c(0.9,0.05,0.05),
                             TaskType = "CPU",
                             EvalMetric = "MAE",
                             GridTune = FALSE,
                             GridEvalMetric = "mae",
                             ModelCount = 1,
                             NTrees = 50,
                             PartitionType = "time")
```
