### ISSUE TITLE
Suggested Changes to AutoTS

### ISSUE THREAD

**Issue by DougVegas** [AdrianAntico/RemixAutoML#2]
#### Runtime Using Walmart Data Set

   user  system elapsed 
  20.23    1.44   21.76 

#### Output Plots

Output plot is base plot from forecast package - need to add RemixTheme to plot.
X axis should display as date, not decimal. 

**Title** of chart should be: 
`paste(FCPeriods, TimeUnit, "forecast for", TargetName, sep = " ")`

**Subtitle** of chart should be: 
`paste("Champion Model:", ChampionModel, "Mean Absolute Percent Error:", paste(round(min(EvaluationMetrics$MAPE),2) * 100, "%", sep = ""), sep = " ") `

**Caption** of chart should be: "Forecast generated by Remix Institute's RemixAutoML R package"

Color of Line should be: #00AA9D

Remix Theme code:

`remix_theme1 = function(){
  theme(
    axis.title = element_text(family = "Helvetica", size = 11),
    axis.text = element_text(family = "Helvetica", size = 11),
    legend.background = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(family = "Helvetica", color = "#1c1c1c", size = 11),
    legend.title = element_blank(),
    legend.justification = 0,
    legend.position = "top",
    #plot.background = element_rect(fill = "#d1d1d1"),
    #panel.background = element_rect(fill= "#d1d1d1"),
    plot.background = element_rect(fill = "#E7E7E7"),
    panel.background = element_rect(fill= "#E7E7E7"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(color = "white"),
    panel.grid.minor.y = element_line(color = "white"),
    plot.title = element_text(family = "Helvetica", color = "#1c1c1c", size = 28, hjust = 0, face = "bold"),
    plot.subtitle = element_text(family = "Helvetica", color = "#1c1c1c", size = 16, hjust = 0),
    plot.caption = element_text(family = "Helvetica", size = 9, hjust = 0, face = "italic")
  )
}
`

#### Issue 1

EvaluationMetrics only include metrics for following models:
- ARIMA
- NN
- ARFIMA
- TBATS
- ETS

No evaluation metrics were outputted for TSLM or PROPHET and SkipModels is set to NULL

#### Feature Request 1
TimeSeriesModel output says:
`Series: dataTSTrain[ ,TargetName]`

Any way to allow this to be dynamic and say what the actual data set and TargetName are called, based on what user puts in?
For example, using the Walmart data set, can it say: 
`Series: walmart_train[, Weekly_Sales]`

#### Feature Request 2

Can we add another output to the list output called "ChampionModel" which is just a character string of the winning model?
(ie ARIMA, NN, ARFIMA, TBATS, ETS, TSLM, PROPHET)

**Comment by AdrianAntico** [comment]
Issue 1: Note that a model may fail to build for a variety of reasons. In the event it doesn't build, it is currently skipped over and no evaluation metrics are returned as a result. 

Looking into the other requests. Will comment when I've evaluated.

**Comment by DougVegas** [comment]
We've decided on not adding in Feature Request 1. 

We'll continue to monitor TSLM and PROPHET for other data sets to see if it continues exhibiting same issue of not outputting evaluation metrics.
