### ISSUE TITLE
AutoKMeans unused argument 

### ISSUE THREAD

**Issue by Bartesto** [AdrianAntico/RemixAutoML#31]
Hi,
Working through your Package Overview course and ran into problems running the ``AutoKMeans()`` example on the Iris data set. 

It gives me the following:
 ``Error in AutoKMeans(data, nthreads = 8, MaxMem = "28G", SaveModels = NULL,  : 
  object 'FilePath' not found``

Under the hood
``if (!is.null(FilePath)) {
    if (!is.character(FilePath)) {
      warning("FilePath needs to resolve to a character value. E.g. getwd()")
    }
  }``

If I comment this out I can get it to run.

Should this have been PathFile from your function params?

Cheers
Bart

**Comment by AdrianAntico** [comment]
@Bartesto Thanks for bringing that up! Looks like I must have changed the name of that argument a while back but didn't update the argument checks at the beginning of the function. I just changed the named in the check to match the argument. Should work fine. Let me know if there is still an issue.

**Comment by Bartesto** [comment]
No worries Adrian! Great package by the way.

**Comment by AdrianAntico** [comment]
@Bartesto thank you!!
