### ISSUE TITLE
Error: package or namespace load failed for 'RemixAutoML' in library.dynam(lib, package, package.lib):  DLL 'RemixAutoML' not found: maybe not installed for this architecture?

### ISSUE THREAD

**Issue by larasatiayudia** [AdrianAntico/RemixAutoML#32]
Hello, i tried installing the package but always failed with error:
**Error: package or namespace load failed for 'RemixAutoML' in library.dynam(lib, package, package.lib):
 DLL 'RemixAutoML' not found: maybe not installed for this architecture?**

I already installed all the dependencies and have no idea where things went wrong. My R env:
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Platform: x86_64-w64-mingw32/x64 (64-bit)

Hope you can solve my problem, thanks

**Comment by AdrianAntico** [comment]
@larasatiayudia I just updated the namespace. You should be able to install now. Let me know if you have any problems and thanks for creating the issue.

**Comment by larasatiayudia** [comment]
@AdrianAntico  it works now, thank you very much!

**Comment by AdrianAntico** [comment]
No problem... Best of luck!
