### ISSUE TITLE
undefined exports: AutoXGBoostClassifier

### ISSUE THREAD

**Issue by lejarx** [AdrianAntico/RemixAutoML#34]
> # Install RemixAutoML:
> devtools::install_github('AdrianAntico/RemixAutoML', upgrade = FALSE, dependencies = FALSE, force = TRUE)
Downloading GitHub repo AdrianAntico/RemixAutoML@master
√  checking for file 'C:\Users\User1\AppData\Local\Temp\RtmpKc3aCz\remotes5c4cb56ae4\AdrianAntico-RemixAutoML-7563aa0/DESCRIPTION' (452ms)
-  preparing 'RemixAutoML': (351ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'RemixAutoML_0.11.0.tar.gz'
   
* installing *source* package 'RemixAutoML' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'RemixAutoML'
    finding HTML links ... done
    AutoCatBoostCARMA                       html  
    AutoCatBoostClassifier                  html  
    AutoCatBoostHurdleModel                 html  
    AutoCatBoostMultiClass                  html  
    AutoCatBoostRegression                  html  
    AutoCatBoostScoring                     html  
    AutoDataPartition                       html  
    AutoH2OMLScoring                        html  
    AutoH2OModeler                          html  
    AutoH2OScoring                          html  
    AutoH2OTextPrepScoring                  html  
    AutoH2oDRFCARMA                         html  
    AutoH2oDRFClassifier                    html  
    AutoH2oDRFHurdleModel                   html  
    AutoH2oDRFMultiClass                    html  
    AutoH2oDRFRegression                    html  
    AutoH2oGBMCARMA                         html  
    AutoH2oGBMClassifier                    html  
    AutoH2oGBMHurdleModel                   html  
    AutoH2oGBMMultiClass                    html  
    AutoH2oGBMRegression                    html  
    AutoKMeans                              html  
    AutoMarketBasketModel                   html  
    AutoNLS                                 html  
    AutoRecomDataCreate                     html  
    AutoRecommender                         html  
    AutoRecommenderScoring                  html  
    AutoTS                                  html  
    AutoTransformationCreate                html  
    AutoTransformationScore                 html  
    AutoWord2VecModeler                     html  
    AutoWordFreq                            html  
    AutoXGBoostCARMA                        html  
    AutoXGBoostClassifier                   html  
    AutoXGBoostHurdleModel                  html  
    AutoXGBoostMultiClass                   html  
    AutoXGBoostRegression                   html  
    AutoXGBoostScoring                      html  
    ChartTheme                              html  
    CreateCalendarVariables                 html  
    CreateHolidayVariables                  html  
    DT_GDL_Feature_Engineering              html  
    DummifyDT                               html  
    EvalPlot                                html  
    GDL_Feature_Engineering                 html  
    GenTSAnomVars                           html  
    ModelDataPrep                           html  
    ParDepCalPlots                          html  
    Partial_DT_GDL_Feature_Engineering      html  
    PrintObjectsSize                        html  
    ProblematicFeatures                     html  
    ProblematicRecords                      html  
    RedYellowGreen                          html  
    RemixAutoML-package                     html  
    RemixTheme                              html  
    ResidualOutliers                        html  
    Scoring_GDL_Feature_Engineering         html  
    SimpleCap                               html  
    TimeSeriesFill                          html  
    multiplot                               html  
    percRank                                html  
    tempDatesFun                            html  
    threshOptim                             html  
    tokenizeH2O                             html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'RemixAutoML' in namespaceExport(ns, exports):
 undefined exports: AutoXGBoostClassifier
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'RemixAutoML' in namespaceExport(ns, exports):
 undefined exports: AutoXGBoostClassifier
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'

**Comment by AdrianAntico** [comment]
@lejarx Hi, sorry about that. I was working on something. You should be able to install without issue now.

**Comment by lejarx** [comment]
Hi @AdrianAntico , no worries, I'm very thankful for the package :). Thanks again! Successfully installed now.

`DONE (RemixAutoML)`

**Comment by AdrianAntico** [comment]
@lejarx Best of luck!
