### ISSUE TITLE
AWS sagemaker instance, fedora: cannot find -lMagick++, cannot find -lMagickCore

### ISSUE THREAD

**Issue by lejarx** [AdrianAntico/RemixAutoML#35]
```
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lMagick++
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lMagickCore
```
I'm trying to install the R package on a AWS sagemaker instance which uses fedora distribution.
I've made sure to install magick by invoking
`sudo yum install ImageMagick-c++-devel`

However I keep getting cannot find-lMagick++ and -lMagickCore, which is a prerequisite to install RemixAutoML.

Anyone has encountered the same and found a solution?

Thanks

**Comment by AdrianAntico** [comment]
@lejarx I have a solution. I just eliminated the magick dependency. I had a single line of code in the AutoTS function to insert an image into the output plot but it's something that isn't necessary and I wasn't exactly impressed with it. I removed that line of code and removed the dependency on the DESCRIPTION file.

**Comment by lejarx** [comment]
@AdrianAntico it's successfully installed now. Thanks bunch!

**Comment by AdrianAntico** [comment]
@lejarx Any chance you can share your insights about installing the package on AWS? I think that would be really helpful to other users. If you would be interested in writing a blog about it I can feature it on our website as well. If you want to remain anonymous I can post it without any of your info. Let me know!
