### ISSUE TITLE
Error message while running code for AutoCatboostCARMA

### ISSUE THREAD

**Issue by trancuuquoc** [AdrianAntico/RemixAutoML#38]
Hi Adrian,
When I run the code, I get an error message:

Error in if (min(as.ITime(data[[eval(DateCols[i])]])) - max(as.ITime(data[[eval(DateCols[i])]])) ==  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
All formats failed to parse. No formats found.

Any suggestion?

---------------

My code is:
library(RemixAutoML)
library(data.table)
data <- data.table::fread("x://Check.csv")
data <- data[, Counts := .N, by = c("Store","Dept")][
  Counts == 138][, Counts := NULL]
keep <- c("Store","Dept","Date","Weekly_Sales")
data <- data[, ..keep]
Results <- RemixAutoML::AutoCatBoostCARMA(
  data,
  TargetColumnName = "Weekly_Sales",
  DateColumnName = "Date",
  GroupVariables = c("Store","Dept"),
  FC_Periods = 30,
  TimeUnit = "day",
  TargetTransformation = TRUE,
  Lags = c(1, 7),
  MA_Periods = c(1, 7),
  CalendarVariables = TRUE,
  TimeTrendVariable = TRUE,
  DataTruncate = FALSE,
  SplitRatios = c(0.7, 0.2, 0.1),
  TaskType = "CPU",
  EvalMetric = "MAPE",
  GridTune = FALSE,
  GridEvalMetric = "mape",
  ModelCount = 1,
  NTrees = 20000,
  PartitionType = "timeseries",
  Timer = TRUE)
CatBoost_Eval <- CatBoostResults$ModelInformation$EvaluationMetricsByGroup
CatBoost_Forecast <- CatBoostResults$Forecast
data.table::fwrite(CatBoost_Eval, paste0(getwd(),"/CatBoost_Eval.csv"))
data.table::fwrite(CatBoost_Forecast, paste0(getwd(),"/CatBoost_Forecast.csv"))
rm(CatBoost_Eval,CatBoostResults)
rm(CatBoost_Forecast,CatBoostResults)

**Comment by AdrianAntico** [comment]
I see you are filtering for store / dept combos that have 138 records based on this line:
data <- data[, Counts := .N, by = c("Store","Dept")][
Counts == 138][, Counts := NULL]

The original article has is filtering for 143 records which is what 95% of the store / dept combos have. So my guess is that there are either no store / dept combos with 138 records or there are some but they have gaps in the data, which might cause a run time error. 

The CARMA function is basically erroring out when it runs the RemixAutoML::CreateHolidayVariables() function.
