### ISSUE TITLE
No Formats Found

### ISSUE THREAD

**Issue by trancuuquoc** [AdrianAntico/RemixAutoML#39]
Hi Adrian,
When I run AutoCatboostCarma, I receive this error:
Error in if (min(as.ITime(data[[eval(DateCols[i])]])) - max(as.ITime(data[[eval(DateCols[i])]])) == :
missing value where TRUE/FALSE needed
In addition: Warning message:
All formats failed to parse. No formats found.
Can you help me to identify this error?
Thank you!
Quoc

**Comment by AdrianAntico** [comment]
@trancuuquoc 

My guess is that one of two things are wrong:
1. You may have not specified the TimeUnit argument correctly. I've seen this error before when I have weekly data and I accidentally specified "day" as the TimeUnit argument.
2. The inner function CreateHolidayVariables() may not be identifying the date column as a Date or POSIXct type. 

I just added in some helper code that should prevent the second error cause from occurring but it won't prevent the error of incorrectly specifying the TimeUnit argument.

**Comment by trancuuquoc** [comment]
Dear Adrian
I just try with the data in attachment of this email.


library(RemixAutoML)
library(data.table)

data <- data.table::fread("c:/Work_Station/Data.csv", header=TRUE,
sep=",",quote="")

keep <- c("Store","Article","Date","Quantity")
data <- data[, ..keep]

CatBoostResults <- RemixAutoML::AutoCatBoostCARMA(
  data,
  TargetColumnName = "Quantity",
  DateColumnName = "Date",
  GroupVariables = c("Store","Article"),
  FC_Periods = 10,
  TimeUnit = "week",
  TargetTransformation = TRUE,
  Lags = c(1:25,51,52,53),
  MA_Periods = c(1:25,51,52,53),
  CalendarVariables = TRUE,
  TimeTrendVariable = TRUE,
  HolidayVariable = FALSE,
  DataTruncate = FALSE,
  SplitRatios = c(0.3, 0.3, 0.4),
  TaskType = "GPU",
  EvalMetric = "RMSE",
  GridTune = FALSE,
  GridEvalMetric = "r2",
  ModelCount = 2,
  NTrees = 1500,
  PartitionType = "timeseries",
  Timer = TRUE)

# Output----
CatBoostResults$TimeSeriesPlot
CatBoost_Results <- CatBoostResults$Forecast
data.table::fwrite(CatBoost_Results,
paste0(getwd(),"/CatBoost_Results.csv"))
rm(CatBoost_Results,CatBoostResults)



----------------------


By the way, I don't know if I have missing values in each article (due to
out of stock), I can run the forecast anyway?

Thank you for your support!

Quoc

**Comment by AdrianAntico** [comment]
@trancuuquoc I didn't receive any data via email. Send it to my email: adrianantico@gmail.com and I'll give it a go and see what the issue is and report back.

**Comment by AdrianAntico** [comment]
@trancuuquoc 

I added the fix. Should work now. You'll have to reinstall the package of course for the changes to take effect.

```
OLD:
# Convert to lubridate as_date() or POSIXct----
  if(is.character(data[[eval(DateColumnName)]])) {
      data[, eval(DateColumnName) := as.Date(get(DateColumnName), tryFormats = x1)]
  } else {
    data[, eval(DateColumnName) := as.POSIXct(get(DateColumnName))]
  }

NEW:
# Convert to lubridate as_date() or POSIXct----
  if (!(tolower(TimeUnit) %chin% c("1min","5min","10min","15min","30min","hour"))) {
    if(is.character(data[[eval(DateColumnName)]])) {
      x <- data[1,get(DateColumnName)]
      x1 <- lubridate::guess_formats(x, orders = c("mdY", "BdY", "Bdy", "bdY", "bdy", "mdy", "dby", "Ymd", "Ydm"))
      data[, eval(DateColumnName) := as.Date(get(DateColumnName), tryFormats = x1)]
    }
  } else {
    data[, eval(DateColumnName) := as.POSIXct(get(DateColumnName))]
  }
```
