### ISSUE TITLE
Error in loadNamespace(name)

### ISSUE THREAD

**Issue by trancuuquoc** [AdrianAntico/RemixAutoML#43]
For the new version, I got this message below:

there is no package called ‘RemixAutoAI’

**Comment by AdrianAntico** [comment]
@trancuuquoc Should be good to go now

**Comment by prankie** [comment]
Hi, I'm still getting the following error when running AutoCatBoostClassifier.

Error in loadNamespace(name) : there is no package called ‘RemixAutoAI’

**Comment by AdrianAntico** [comment]
@prankie I just removed that dependency. Go ahead and reinstall and you should be good to go. Let me know if you catch anything else! Thanks
