### ISSUE TITLE
Regressor variables in CARMA models

### ISSUE THREAD

**Issue by mbanco** [AdrianAntico/RemixAutoML#44]
Hi Adrian,
Is it possible to include regressors in the CARMA models?

Best Regards

Mauricio

**Comment by AdrianAntico** [comment]
@mbanco I am planning to release some significant features to the CARMA functions pretty soon. As for the regressors, there are two types and I will be releasing the first one from below and working on the second one. 

Types of regressors for the CARMA suite:
1. User supplied values that span both historically and into the future. Basically the user needs to supply the historical values and values that span the entire forecast horizon.
2. User supplied values that span historically only. The user will specify which forecasting algorithm to utilize to forecast the user supplied values into the future that covers the forecast horizon. Those values will then be used in the CARMA functions. This one is going to take quite a bit more work so I'm reserving this one for later (tbd).

**Comment by mbanco** [comment]
Excellent job!

Thank you very much.

**Comment by AdrianAntico** [comment]
@mbanco new carma models have this starting on release 0.2.0+. Currently, only AutoCatBoostCARMA() is ready but the others are almost passing all tests.

**Comment by mbanco** [comment]
Excellent job!! Thank you very much!!
