### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by VladPerervenko** [AdrianAntico/RemixAutoML#45]
`** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'RemixAutoML' in namespaceExport(ns, exports):
 undefined exports: AutoXGBoostMultiClass`
Error in the package or for my part?

**Comment by AdrianAntico** [comment]
@VladPerervenko  You should be good to go now. I fixed the imports.R file and had to update the roxygen2 header information for the XGBoost Multiclass function.
