### ISSUE TITLE
Prophet and fasster models 

### ISSUE THREAD

**Issue by chalioui** [AdrianAntico/RemixAutoML#46]
Thank you for this great job! can you add prophet and fasster models in your autoTS function   (https://github.com/tidyverts/fasster, https://github.com/facebook/prophet )

**Comment by DougVegas** [comment]
Thank you @chalioui . One of our earlier prototype versions of AutoTS leveraged prophet but was removed in subsequent versions. We'll add this to the list of possible enhancements we can make to package.

**Comment by AdrianAntico** [comment]
@chalioui Check out the new AutoBanditArima() model I just released... Let me know if you have any new ideas based on the release of that.
