### ISSUE TITLE
AutoXGBoostCARMA fails

### ISSUE THREAD

**Issue by spsanderson** [AdrianAntico/RemixAutoML#47]
I am using the AutoXGBoostCARMA to forecast a time series. Yet when I do I get the following failure:
```
Error in if (rng.nch[1] != rng.nch[2]) stop("'charvec' has non-NA entries of different number of characters") : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In `[.data.table`(TestDataEval, , `:=`(Target, NULL)) :
  Column 'Target' does not exist to remove
2: In `[.data.table`(Preds, , `:=`(eval(DateColumnName), NULL)) :
  Column 'Date_Column' does not exist to remove
```
I run the following command:

```
AutoXGBoostCARMA(
  data = tidy_model_tbl
  , TargetColumnName = "Value"
  , DateColumnName = "Date_Column"
  , GroupVariables = "data_type"
  , FC_Periods = ifelse(time_param == "weekly", 52, 12)
  , TimeUnit = ifelse(time_param == "weekly", "week", "month")
)
```

My data is attached.
[tidy_model_tbl.xlsx](https://github.com/AdrianAntico/RemixAutoML/files/4072951/tidy_model_tbl.xlsx)

**Comment by AdrianAntico** [comment]
@spsanderson Thanks for bringing this up. I have some upgrades for the carma functions that I'm going to be releasing soon.

**Comment by spsanderson** [comment]
Excellent!

Steven P Sanderson II, MPH

**Comment by AdrianAntico** [comment]
@spsanderson The AutoXGBoostCARMA() function is good to go. Keep in mind, there are some new arguments so check out the help file - I have an example setup of the function with the arguments grouped by purpose.
