### ISSUE TITLE
AutoKMeans produces 0 clusters

### ISSUE THREAD

**Issue by spsanderson** [AdrianAntico/RemixAutoML#48]
When using the following function with the following parameters:

```
AutoK_obj <- RemixAutoML::AutoKMeans(
    data = customer_product_tbl %>% select(-bikeshop_name)
    , KMeansK = 15
    , KMeansMetric = "tot_withinss"
    , GridTuneGLRM = TRUE
    , GridTuneKMeans = TRUE
    )
```

I get only 0 returned in the cluster column. Yet when I run a skree plot I can see that there are at least 3 or 4 as a good cut off.

```
kmeans_mapper <- function(centers = 3) {
    
    # Body
    customer_product_tbl %>%
        select(-bikeshop_name) %>%
        kmeans(
            centers = centers
            , nstart = 100
        )
    
}
kmeans_mapper(3) %>% glance()

# Mapping the function to many elements
kmeans_mapped_tbl <- tibble(centers = 1:15) %>%
    mutate(k_means = centers %>% map(kmeans_mapper)) %>%
    mutate(glance = k_means %>% map(glance))

# Skree Plot ----
kmeans_mapped_tbl %>%
    unnest(glance) %>%
    select(centers, tot.withinss) %>%
    ggplot(
        mapping = aes(
            x = centers
            , y = tot.withinss
        )
    ) +
    geom_point() +
    geom_line() +
    ggrepel::geom_label_repel(mapping = aes(label = centers)) +
    theme_tq()
````

The data is a user-item matrix form.

[customer_trends_tbl.xlsx](https://github.com/AdrianAntico/RemixAutoML/files/4104563/customer_trends_tbl.xlsx)

**Comment by DougVegas** [comment]
Hi @spsanderson 

Looking into issue now. However, I think the data set you provided isn't the correct one? You provided customer_trends_tbl but the AutoKMeans example uses a data set named customer_product_tbl

I can't reproduce the error because there is no column called bikeshop_name

**Comment by spsanderson** [comment]
Oh boy let me look into it and fix

Steven P Sanderson II, MPH

**Comment by spsanderson** [comment]
[customer_product_tbl.xlsx](https://github.com/AdrianAntico/RemixAutoML/files/4104806/customer_product_tbl.xlsx)

This is the correct file

**Comment by AdrianAntico** [comment]
@spsanderson Why is the data in the form that it is? What do the values in each column represent?

**Comment by spsanderson** [comment]
proportions of purchases of each bike model from a bikeshop

**Comment by AdrianAntico** [comment]
I wouldn't aggregate the data before running k-means. I would use the transactional data

**Comment by spsanderson** [comment]
I will try it and report back

**Comment by AdrianAntico** [comment]
Sounds good

**Comment by spsanderson** [comment]
My data looks like the attached, should I make my data strictly the quantity column (this is what I am aggregating)


[bike_orderlines_tbl.xlsx](https://github.com/AdrianAntico/RemixAutoML/files/4105301/bike_orderlines_tbl.xlsx)

**Comment by spsanderson** [comment]
So with the following code and attached data I get 2 clusters 0 and 1, it should really be at least 4. Which is what I get from the method posted in the original post.

```
AutoK_obj <- RemixAutoML::AutoKMeans(
    data = customer_trends_tbl %>% select(-prop_of_total)
    , KMeansK = 15
    , KMeansMetric = "tot_withinss"
    , GridTuneGLRM = TRUE
    , GridTuneKMeans = TRUE
    )
```

[customer_trends_tbl.xlsx](https://github.com/AdrianAntico/RemixAutoML/files/4106707/customer_trends_tbl.xlsx)

**Comment by AdrianAntico** [comment]
@spsanderson I would start tinkering with the arguments. What's going on internally is that a GLRM model from H2O is built first (for the purposes of dimensionality reduction) and you select the number of factors from that to keep and pass on to the KMEANS algo from H2O, which will run to find the optimal k using the factors data from the GLRM.

If you go through the help file (?RemixAutoML::AutoKMeans), you can read up on what each argument does. The function is intended to be flexible for most kinds of data sets but you will want to try several settings if you don't already have a good idea of how to set it for your particular case.

This function is just a beginning for unsupervised learning. I spend most of my time working on the supervised learning stuff since I encounter it more often in practice, but I will get around to enhancing these at some point. If you are interested in helping out let me know. 

```
AutoKMeans <- function(data,
                       nthreads        = 8,
                       MaxMem          = "28G",
                       SaveModels      = NULL,
                       PathFile        = NULL,
                       GridTuneGLRM    = TRUE,
                       GridTuneKMeans  = TRUE,
                       glrmCols        = c(1:5),
                       IgnoreConstCols = TRUE,
                       glrmFactors     = 5,
                       Loss            = "Absolute",
                       glrmMaxIters    = 1000,
                       SVDMethod       = "Randomized",
                       MaxRunTimeSecs  = 3600,
                       KMeansK         = 50,
                       KMeansMetric    = "totss") {
```

**Comment by spsanderson** [comment]
Thanks for the update I will take through and take a look. And see what I
can come up with.

Steven P Sanderson II, MPH

**Comment by spsanderson** [comment]
Working through it. Seems that even on the Iris dataset the h2o::kmeans is only producing 2 clusters when we know there are 3. I forked and cloned repo. Will work on it.
