### ISSUE TITLE
How to change the caption on the ggplot?

### ISSUE THREAD

**Issue by FelipeCarrillo** [AdrianAntico/RemixAutoML#5]
Hi; 
I found your post on Rbloggers and also on your website. I was able to install all of the packages although catboost was a challenge. It is a great demo and going through it right now. I have a naive question though. I looked at the str of the model and see all the captions you are using for the plot. How do I change or customize the captions you have on the title area and by the X axis area? I want to customize this plot to my own data. Thanks beforehand.

**Comment by AdrianAntico** [comment]
# Run the below code to start, as an example
# The output will be stored in the object output <- AutoTS()
data <- data.table::data.table(DateTime = as.Date(Sys.time()),
  Bla = stats::filter(rnorm(1000,
                               mean = 50,
                               sd = 20),
                         filter=rep(1,10),
                         circular=TRUE))
data[, temp := seq(1:1000)][, DateTime := DateTime - temp][, temp := NULL]
data <- data[order(DateTime)]
output <-   AutoTS(data,
                   TargetName       = "Bla",
                   DateName         = "DateTime",
                   FCPeriods        = 30,
                   HoldOutPeriods   = 1,
                   EvaluationMetric = "MSE",
                   TimeUnit         = "day",
                   Lags             = 1,
                   SLags            = 1,
                   NumCores         = 4,
                   SkipModels       = c("NNET","TBATS","ETS","TSLM","ARFIMA","DSHW"),
                   StepWise         = TRUE,
                   TSClean          = TRUE,
                   ModelFreq        = TRUE,
                   PrintUpdates     = TRUE)

# Next, overwrite or change the existing labels and title / subtitle / caption
ForecastPlot <- ForecastPlot + ggplot2::labs(x="Some other time frame?", 
                                             y="Some other dependent variable",
                                             title="My awesome plot",
                                             subtitle = "", 
                                             caption = "")

**Comment by FelipeCarrillo** [comment]
Awesome!!!
I had found another way but your way is much better. Thanks for the great post, totally great!!!!
