### ISSUE TITLE
Error in loadNamespace(name) : there is no package called ‘RemixAutoAI’

### ISSUE THREAD

**Issue by DrRoad** [AdrianAntico/RemixAutoML#50]

**Comment by AdrianAntico** [comment]
@DrRoad Can you try to install again for me? I just did several find and replaces. I have a private repo called RemixAutoAI that I use to test these out on before I move over here. I won't get the error however since I have the AI version on my local...

**Comment by DrRoad** [comment]
![2020-02-24_154126](https://user-images.githubusercontent.com/8111532/75125870-29c99900-571c-11ea-909e-8e527710f995.png)
I got this fatal error after reinstalling and rerunning the AutoCatBoostCARMA example

**Comment by AdrianAntico** [comment]
That happens when you run it without data. The example in the help file is to show you how to set up the arguments. Data doesn't come with the function.
