### ISSUE TITLE
Error in AutoXGBoostRegression function

### ISSUE THREAD

**Issue by mbanco** [AdrianAntico/RemixAutoML#54]
Hi Adrian,
there is an error with this code:

> Correl <- 0.85
> N <- 10000
> data <- data.table::data.table(Target = runif(N))
> data[, x1 := qnorm(Target)]
> data[, x2 := runif(N)]
> data[, Independent_Variable1 := log(pnorm(Correl * x1 +
+                                               sqrt(1-Correl^2) * qnorm(x2)))]
> data[, Independent_Variable2 := (pnorm(Correl * x1 +
+                                            sqrt(1-Correl^2) * qnorm(x2)))]
> data[, Independent_Variable3 := exp(pnorm(Correl * x1 +
+                                               sqrt(1-Correl^2) * qnorm(x2)))]
> data[, Independent_Variable4 := exp(exp(pnorm(Correl * x1 +
+                                                   sqrt(1-Correl^2) * qnorm(x2))))]
> data[, Independent_Variable5 := sqrt(pnorm(Correl * x1 +
+                                                sqrt(1-Correl^2) * qnorm(x2)))]
> data[, Independent_Variable6 := (pnorm(Correl * x1 +
+                                            sqrt(1-Correl^2) * qnorm(x2)))^0.10]
> data[, Independent_Variable7 := (pnorm(Correl * x1 +
+                                            sqrt(1-Correl^2) * qnorm(x2)))^0.25]
> data[, Independent_Variable8 := (pnorm(Correl * x1 +
+                                            sqrt(1-Correl^2) * qnorm(x2)))^0.75]
> data[, Independent_Variable9 := (pnorm(Correl * x1 +
+                                            sqrt(1-Correl^2) * qnorm(x2)))^2]
> data[, Independent_Variable10 := (pnorm(Correl * x1 +
+                                             sqrt(1-Correl^2) * qnorm(x2)))^4]
> data[, Independent_Variable11 := as.factor(
+     ifelse(Independent_Variable2 < 0.20, "A",
+            ifelse(Independent_Variable2 < 0.40, "B",
+                   ifelse(Independent_Variable2 < 0.6,  "C",
+                          ifelse(Independent_Variable2 < 0.8,  "D", "E")))))]
> data[, ':=' (x1 = NULL, x2 = NULL)]

> TestModel <- AutoXGBoostRegression(data,
+                                    TrainOnFull = FALSE,
+                                    ValidationData = NULL,
+                                    TestData = NULL,
+                                    TargetColumnName = "Target",
+                                    FeatureColNames = 2:12,
+                                    IDcols = NULL,
+                                    ReturnFactorLevels = FALSE,
+                                    TransformNumericColumns = NULL,
+                                    eval_metric = "RMSE",
+                                    Trees = 50,
+                                    GridTune = TRUE,
+                                    grid_eval_metric = "mae",
+                                    MaxModelsInGrid = 10,
+                                    NThreads = max(1, parallel::detectCores()-2),
+                                    TreeMethod = "hist",
+                                    model_path = NULL,
+                                    metadata_path = NULL,
+                                    ModelID = "FirstModel",
+                                    NumOfParDepPlots = 3,
+                                    ReturnModelObjects = TRUE,
+                                    SaveModelObjects = FALSE,
+                                    PassInGrid = NULL)
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
Error in get(Target) : primer argumento inválido

Best Regards

Mauricio

**Comment by AdrianAntico** [comment]
@mbanco Change the target variable name to something else. The function runs into error when the name Target is used for the target variable.
