### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by AjayKMehta** [AdrianAntico/RemixAutoML#55]
Thanks for your work in creating this library.

I tried to install the package using the instructions in README.md but I am getting the following error:

```shell
* installing *source* package 'RemixAutoML' ...
** R
Error in parse(outFile) : 
  C:/Users/Ajay/AppData/Local/Temp/Rtmp4mKcfB/R.INSTALLb390631b7c86/RemixAutoML/R/EconometricsFunctions.R:1024:89: unexpected ']'
1023:   if(ModelFreq) {
1024:     ModelFreqFrequency <- forecast::findfrequency(data_train[, get(names(data_train)[2L]]
```

There is a missing ')' in `forecast::findfrequency(data_train[, get(names(data_train)[2L]]` in EconometricsFunctions.R.

**Comment by AdrianAntico** [comment]
@AjayKMehta  I see the error. Give a few minutes. I made an update to that today. Looks like I forgot a parenthesis

**Comment by AdrianAntico** [comment]
@AjayKMehta give it a try now. Should be good to go

**Comment by AjayKMehta** [comment]
It works fine now. Thanks!

**Comment by AdrianAntico** [comment]
@AjayKMehta No problem. Let me know if you have any questions about the package

**Comment by AjayKMehta** [comment]
@AdrianAntico I plan to check this out when I have some free time. Will definitely reach out if I have any questions.
