### ISSUE TITLE
Certain functions change working directory and do not change it back

### ISSUE THREAD

**Issue by JerroldJV** [AdrianAntico/RemixAutoML#6]
In 3 places in the code base, there is the following code:
```
if (SaveModelObjects) {    
    setwd(model_path)  
    catboost::catboost.save_model(model = model, model_path = paste0(ModelID))  
}
```
The problem with this code is that the working directory is changed, and not changed back.  This is of particular concern because if "model_path" is a relative directory, this code can only be run once before it starts failing. E.g. if my current working directory is "C:/", and model_path = "some_folder", after this code is run once the current working directory is "C:/some_folder".  The next time this code runs, it will try to set the working directory to a non-existent folder, "C:/some_folder/some_folder".

I think there are two ways to fix this approach:
```
if (SaveModelObjects) {
    oldwd <- getwd()
    setwd(model_path)
    catboost::catboost.save_model(model = model, model_path = paste0(ModelID))
    setwd(oldwd)
}
```

Or

```
if (SaveModelObjects) {
    model_path = paste0(model_path, '/', ModelID)
    catboost::catboost.save_model(model = model, model_path = model_path)
}
```

If this works correctly, I think the second approach has fewer chance of side-effects.

**Comment by AdrianAntico** [comment]
Thanks @JerroldJV !! Great catch

The setwd() was originally in the AutoCatBoostRegression(), AutoCatBoostClassifier(), and AutoCatBoostMultiClass() functions. The code is now written as the below for all three catboost auto functions, per your suggestion:
```{r}
if(SaveModelObjects) {
    catboost::catboost.save_model(model = model, model_path = paste0(model_path, "/", ModelID))
}
```
