### ISSUE TITLE
How to integrate regressors to the time series forecast models?

### ISSUE THREAD

**Issue by lejarx** [AdrianAntico/RemixAutoML#61]
Hi @AdrianAntico,

Do you have a guide on how can I include regressors to the forecast models in this package?

**Comment by AdrianAntico** [comment]
@lejarx check out the help file for AutoCatBoostCARMA(). I set up examples there. Look for the xregs argument. The xregs needs to be a data.table and has to extend into the future enough to cover the FC_Window periods to forecast. If you have categorical variables (like "Store" or "Dept") make sure to set up xregs with both categorical columns and the other regressors that you want to use. Let me know if that helps out.

**Comment by lejarx** [comment]
Thanks @AdrianAntico 

```
Additional data to use for model development and forecasting. Data needs to be a complete series which means both the historical and forward looking values over the specified forecast window needs to be supplied.
--
```
By forward looking values, this means we already need to have the future forecasted values for each of the regressors correct?

Otherwise, do you maintain a list of the models that support XREG?

**Comment by AdrianAntico** [comment]
@lejarx The Auto__CARMA() suite supports these xregs for forecasting.

The individual regressions supplied in the xregs argument needs to already be forecasted ahead. If you don't have forward looking regressions you can forecast them out or you could try using lags instead. For the lag method, let's say you want to forecast out 5 weeks into the future, this means you would need to utilize lags greater than 5 weeks, such as lag_6, lag_7, ... , lag_n. Make sure to inpute any missing values at the earliest time periods that you might generate when creating the lags.

**Comment by lejarx** [comment]
Thanks @AdrianAntico , appreciate your thoughtful response!

**Comment by AdrianAntico** [comment]
@lejarx No problem, best of luck!
