### ISSUE TITLE
h2o

### ISSUE THREAD

**Issue by VladPerervenko** [AdrianAntico/RemixAutoML#64]
Correct
`install.packages("h2o", type="source", repos="http://h2o-release.s3.amazonaws.com/h2o/rel-zahradnik/6/R")`

**Comment by AdrianAntico** [comment]
@VladPerervenko Can I get a little more context? Is that the most recent update or something else?

**Comment by VladPerervenko** [comment]
Latest release[ h2o (3.30.0.6)](http://h2o-release.s3.amazonaws.com/h2o/rel-zahradnik/6/index.html)
Copy and paste these commands into R one line at a time:
`# The following two commands remove any previously installed H2O packages for R.
if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }

# Next, we download packages that H2O depends on.
pkgs <- c("RCurl","jsonlite")
for (pkg in pkgs) {
if (! (pkg %in% rownames(installed.packages()))) { install.packages(pkg) }
}

# Now we download, install and initialize the H2O package for R.
install.packages("h2o", type="source", repos="http://h2o-release.s3.amazonaws.com/h2o/rel-zahradnik/6/R")

# Finally, let's load H2O and start up an H2O cluster
library(h2o)
h2o.init()`
And of course you need to have a use case with [Spark 3.0.](https://s3.amazonaws.com/h2o-release/sparkling-water/spark-3.0/3.30.0.6-1-3.0/index.html)

**Comment by AdrianAntico** [comment]
@VladPerervenko Based on this page https://docs.h2o.ai/h2o/latest-stable/h2o-docs/faq/r.html the code to install is below. Not sure what webpage you found the install code you provided...

install.packages("h2o", type = "source", repos = (c("http://h2o-release.s3.amazonaws.com/h2o/latest_stable_R)))
