### ISSUE TITLE
Lost dependency

### ISSUE THREAD

**Issue by TheofilosMyrillas** [AdrianAntico/RemixAutoML#7]
Hi,
I try to install devtools::install_github('AdrianAntico/RemixAutoML', force = TRUE, dependencies = TRUE, upgrade = FALSE) but i get this error:
Error: (converted from warning) unable to access index for repository https://github.com/catboost/catboost/tree/master/catboost/R-package/src/contrib:
  cannot open URL 'https://github.com/catboost/catboost/tree/master/catboost/R-package/src/contrib/PACKAGES'

**Comment by AdrianAntico** [comment]
Hi @TheofilosMyrillas did you run the first script to install the dependencies? It looks like you don't have catboost installed.

```{r}
library(devtools)
# No Remotes ----
# Attachments ----
to_install <- c("catboost", "caTools", "data.table", "doParallel", "foreach", "forecast", "ggplot2", "h2o", "itertools", "lubridate", "monreg", "pROC", "RColorBrewer", "recommenderlab", "ROCR", "scatterplot3d", "stringr", "tm", "tsoutliers", "wordcloud", "xgboost", "zoo")
for (i in to_install) {
  message(paste("looking for ", i))
  if(i == "catboost" & !requireNamespace(i)) {
    devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
  } else if(i == "h2o" & !requireNamespace(i)) {
    if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
    if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }
    pkgs <- c("RCurl","jsonlite")
    for (pkg in pkgs) {
      if (! (pkg %in% rownames(installed.packages()))) { install.packages(pkg) }
    }
    install.packages("h2o", type="source", repos="https://h2o-release.s3.amazonaws.com/h2o/rel-yates/3/R")
  } else if (!requireNamespace(i)) {
    message(paste("     installing", i))
    install.packages(i)
  }
}
```

**Comment by TheofilosMyrillas** [comment]
Hi @AdrianAntico, all packages are installed. I run the script you mentioned before installing your package. My collegue face the same problem. 
Maybe I am wrong but I believe that the problem is that  it tries to find this url 'https://github.com/catboost/catboost/tree/master/catboost/R-package/src/contrib/PACKAGES' but does not exist.
![image](https://user-images.githubusercontent.com/15029814/58865479-4a9a1c00-86bf-11e9-8598-46e01a08bcd0.png)

**Comment by AdrianAntico** [comment]
Can you investigate these links and let me know if neither works for you?

This link shows the way I have listed in the installation script: 
https://catboost.ai/docs/installation/r-installation-github-installation.html
``` {r}
devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
```

Here is a link to another way:
https://catboost.ai/docs/installation/r-installation-binary-installation.html
``` {r}
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.6.1.1/catboost-R-Windows-0.6.1.1.tgz', args = c("--no-multiarch"))
```

**Comment by TheofilosMyrillas** [comment]
Hi, I managed to install your package by setting dependencies = FALSE. Everything works now. Thanks

**Comment by labrax** [comment]
I had some issues installing it. I fixed installing dependencies on my installation (apt-get install libgsl0-dev) and a packages that were missing - install.packages("sde").

Thank you
