### ISSUE TITLE
Confidence level and forecast function

### ISSUE THREAD

**Issue by mbanco** [AdrianAntico/RemixAutoML#71]
Hi Adrian,
Would it be possible to allow the AutoArfima, AutoTBATS, AutoBanditNNet and AutoBanditSarima functions to include the possibility of modifying the confidence level and also include the forecast function, as in the forecast package?

Best regards,

Mauricio

**Comment by AdrianAntico** [comment]
@mbanco Selecting the confidence levels is a great idea. I think it should be straightforward to add. 

What do you mean by adding the forecast function though? Returning the model?

**Comment by mbanco** [comment]
Thanks Adrian,
This is the forecast function included in the forecast package:

forecast(
  object,
  h = ifelse(frequency(object) > 1, 2 * frequency(object), 10),
  level = c(80, 95),
  xreg = NULL,
  ...
)

This allows modifying the confidence level or the value of the regressors, etc without having to refit the model.

**Comment by AdrianAntico** [comment]
@mbanco Can I just return the model object and the xreg object as well? If you have those two then you can run the forecast function without refitting

**Comment by mbanco** [comment]
If you can return the model object and the xreg object, that would be very good!!

**Comment by AdrianAntico** [comment]
@mbanco Let me start by adding a Path argument to the functions so that the model and xregs can be saved to a file location of your choice if a path is supplied. I can do that quickly.

**Comment by AdrianAntico** [comment]
@mbanco You can now supply a path to the FilePath arg and the model will be saved and if there are XREG and XREGFC objects, those too (or two) will be saved to file.

Let me know if that works for both requests. With the model output you can reforecast and supply different prediction interval values.

**Comment by mbanco** [comment]
Thank you very much, Adrian!
I'm going to try this version.

Regards

**Comment by AdrianAntico** [comment]
Let me know how it goes. I think you will need to run RemixAutoML::TimeSeriesDataPrepare() to get the training data to run the forecast() function. I think the PerformanceGrid output from the AutoBandit_() and Auto_() functions will let you know how to set the params in TimeSeriesPrepare(). Let me know if you can't get that to work..
