### ISSUE TITLE
Error catboost.train

### ISSUE THREAD

**Issue by PyntieHet** [AdrianAntico/RemixAutoML#73]
![image](https://user-images.githubusercontent.com/82921259/115488458-847b5980-a228-11eb-84d0-ceef8278218d.png)

I am running through the example workflow as I want to replicate for a task elsewhere but I am running into this error right as it begins the training step. I've tried adjusting this parameter but it all seems to fail here.

Thank you,
Ryan

**Comment by AdrianAntico** [comment]
Hi @PyntieHet 

Someone else reached out about that issue via email to me. I'm not sure exactly which release the CatBoost team made where they added the langevin argument but if you install their most recent version, the issue will not longer exist and you'll have the added benefit of their upgrades. Looks like it might have been 0.24 (https://github.com/catboost/catboost/releases). 

However this does remind me to update the code below that I post on the readme. I need to update it to V0.25.1 now that it actually runs without error. I typically report issues to the CatBoost folks as soon as I come across them. For example, here's an issue thread with version 0.24.4 and 0.25 not working correctly. https://github.com/catboost/catboost/issues/1525

```
install.packages("https://github.com/catboost/catboost/releases/download/v0.24.3/catboost-R-Windows-0.24.3.tgz", repos = NULL, type = "source", INSTALL_opts = c("--no-multiarch", "--no-test-load"))
```

**Comment by AdrianAntico** [comment]
@PyntieHet I should ask - are you allowed to upgrade catboost? I haven't had anyone tell me they couldn't but if you can't, I can always add some code to ignore that argument for people with earlier versions of catboost.
