### ISSUE TITLE
[Thanks] Great library

### ISSUE THREAD

**Issue by talegari** [AdrianAntico/RemixAutoML#80]
This is not an issue, but a heartfelt thank you note.

[RemixAutoML](https://github.com/AdrianAntico/RemixAutoML) is helping to get to my first exploratory models quickly, set the benchmarks. Its well written. Thanks for this wonderful library Adrian.

Hope to see this on CRAN some day. Keep up the good work.

**Comment by AdrianAntico** [comment]
Thank you!
